#!/bin/bash

## Finds homologues in Phytozome

## Takes Phytozome proteome ID(s) (and optional lookup file if proteome ID not in default lookup file)
## Takes Arabidopsis AGI gene ID(s)
## Extracts query Arabidopsis protein sequence(s)
## Downloads Phytozome proteome's proteome, genome, and GFF
## Executes reciprocal protein blast on proteome using Arabidopsis protein as query
## Maps Phytozome homologue transcript ID(s) to gene ID(s)
## Extracts GFF of relevant gene(s) from Phytozome proteome
## Subsets genome according to GFF
## Optionally generates genbank file(s)
## Removes downloaded files

## TODO: some tmp files are created in the process of this script and not deleted. possibly generated by annotation.py or reference.py. see https://docs.python.org/3.6/library/weakref.html#comparing-finalizers-with-del-methods for how we can maybe delete tmp files/directories when object is no longer being referenced (i.e. effectively deleted).

jgi_token=/home/rachelle/tokens/jgi_gold_api.txt
rblastgen=/mnt/chaelab/rachelle/scripts/recip_blast/recip_blast_gen.sh
subset_gff=/mnt/chaelab/rachelle/src/subset_gff.sh
get_seq=/mnt/chaelab/rachelle/scripts/get_seqs_generic/get_seqs.sh

OFFLINE_TOKEN=$(cat ${jgi_token})
ACCESS_TOKEN=$(curl https://gold-ws.jgi.doe.gov/exchange?offlineToken=$OFFLINE_TOKEN)

GFF_DEFAULT=/mnt/chaelab/shared/genomes/TAIR10/features/TAIR10_GFF3_genes.gff
FASTA_DEFAULT=/mnt/chaelab/shared/genomes/TAIR10/fasta/a_thaliana_all.fasta
PEP_DEFAULT=/mnt/chaelab/shared/genomes/TAIR10/fasta/TAIR10_pep_20101214.fasta
GENOME_LOOKUP_DEFAULT=/mnt/chaelab/rachelle/data/Phytozome/phytozome14/Current_Genomes.unrestricted.assembly-gff-prot_available-standardised.curated.tsv
PHY_LOOKUP_DEFAULT='/mnt/chaelab/rachelle/data/Phytozome/phytozome14/filelist_assembly-fa.latest-standardised.tsv /mnt/chaelab/rachelle/data/Phytozome/phytozome14/filelist_geneExon-gff.latest-standardised.tsv /mnt/chaelab/rachelle/data/Phytozome/phytozome14/filelist_protein-fa.latest-standardised.tsv'
PROTEOME_ID_DEFAULT=all
PROCESSES_DEFAULT=1
EXTEND_BP_DEFAULT=0
FLANK_BP_DEFAULT=500
GENBANK_OUT_DEFAULT=0
# EXTEND_PARENT_DEFAULT=1
MEMSAVE_DEFAULT=1
SORT_DEFAULT=0
THRESHOLD_DEFAULT=511999999 ## maximum chromosome size for bedtools without -sorted option is 512 Mb (https://bedtools.readthedocs.io/en/latest/)

while (( "$#" )); do
    case "$1" in
        --gff) GFF="$(realpath ${2})"; shift;; ## input GFF3 file of reference organism (TAIR10 default)
        --fasta) FASTA="$(realpath ${2})"; shift;; ## input FASTA file of reference assembly (TAIR10 default)
        --pep) PEP="$(realpath ${2})"; shift;; ## input FASTA file of reference proteome (TAIR10 default)
        --query-pep) PEP_QUERY="$(realpath ${2})"; shift;; ## input FASTA file of query protein sequences (not compatible with GID and F_GID)
        --id-file) F_GID="$(realpath ${2})"; shift;; ## input TXT file of gene IDs (1 ID per line)
        --id) GID="${2}"; shift;; ## comma-separated gene IDs
        --genome-lookup) GENOME_LOOKUP="$(realpath ${2})"; shift;; ## file with genome IDs in 2nd column (with colname row)
        --phytozome-lookup) PHY_LOOKUP="$(realpath ${2})"; shift;; ## lookup files (lookup files for assembly, GFF, and protein fasta required; provided as a string separated by space)
        -p|--proteome) PROTEOME_ID="${2}"; shift;; ## comma-separated phytozome proteome IDs
        --process) PROCESSES="${2}"; shift;; ## number of parallel processes
        --extend) EXTEND_BP="${2}"; shift;; ## number of bp to extend for feature subsetting
        --flank) FLANK_BP="${2}"; shift;; ## number of bp to extend beyond extended features for FASTA subsetting
        --dir) DIR="$(realpath ${2})"; shift;; ## output directory
        --gb|--genbank) GENBANK_OUT=1;; ## output genbank files
        --memsave) MEMSAVE=1;; ## use memsave mode
        --no-memsave) MEMSAVE=0;; ## don't use memsave mode
        ## sorts GFF3 file and then pass -sorted argument and sorted GFF3 file to bedtools intersect
        --sort) SORT=1;;
        ## chromosome size threshold for automatically setting SORT=1
        --sort-threshold|--threshold) THRESHOLD="${2}"; shift;;
    esac
    shift
done

## set some variables with defaults
GFF="${GFF:-${GFF_DEFAULT}}"
FASTA="${FASTA:-${FASTA_DEFAULT}}"
PEP="${PEP:-${PEP_DEFAULT}}"
GENOME_LOOKUP="${GENOME_LOOKUP:-${GENOME_LOOKUP_DEFAULT}}"
PHY_LOOKUP="${PHY_LOOKUP:-${PHY_LOOKUP_DEFAULT}}"
PROTEOME_ID="${PROTEOME_ID:-${PROTEOME_ID_DEFAULT}}"
GENBANK_OUT="${GENBANK_OUT:-${GENBANK_OUT_DEFAULT}}"
PROCESSES="${PROCESSES:-${PROCESSES_DEFAULT}}"
FLANK_BP="${FLANK_BP:-${FLANK_BP_DEFAULT}}"
EXTEND_BP="${EXTEND_BP:-${EXTEND_BP_DEFAULT}}"
MEMSAVE=${MEMSAVE:-${MEMSAVE_DEFAULT}}
SORT=${SORT:-${SORT_DEFAULT}}
THRESHOLD=${THRESHOLD:-${THRESHOLD_DEFAULT}}

## check that required arguments are provided
if [ -z ${GFF} ]; then
    echo "Input GFF3 file is required."
    exit 1
elif [ -z ${FASTA} ]; then
    echo "Input FASTA file is required."
    exit 1
elif [ -z ${PEP_QUERY} ] && [ -z ${F_GID} ] && [ -z ${GID} ]; then
    echo "Input protein FASTA file or gene ID file (1 ID per line) or string of comma-separated gene IDs is required."
    exit 1
elif [ ! -z ${PEP_QUERY} ] && ( [ ! -z ${F_GID} ] || [ ! -z ${GID} ] ); then
    echo "Input protein FASTA file (--pep-query) is incompatible with gene ID file (--id-file) and string of gene IDs (--id)."
    exit 1
elif [ -z ${DIR} ]; then
    echo "Output directory is required."
    exit 1
fi

## create temporary directory
mkdir ${DIR}
dir_tmp=${DIR}/tmp
mkdir -p ${dir_tmp}
echo "============::=== Working directory: '${DIR}' ==::============"
function mktemp_f { echo "$(mktemp -p ${dir_tmp})"; }

## cleanup
# function cleanup_delete { echo "Removing temporary directory '${dir_tmp}'"; rm -r ${dir_tmp}; }
# function cleanup_move { echo "Moving temporary directory '${dir_tmp}' to '${DIR}'";
#                         rm -r ${dir_tmp}/tmp; mv ${dir_tmp} ${DIR}; }
# if [ -z ${DIR} ]; then ## since we require DIR, we shouldn't encounter this
#     trap cleanup_delete EXIT
#     trap cleanup_delete SIGINT
# else
#     trap cleanup_move EXIT
#     trap cleanup_move SIGINT
# fi
## since we're writing directly to output directory, just delete the tmp directory inside it
function cleanup_delete_tmp { echo "Removing temporary directory '${dir_tmp}'"; rm -r ${dir_tmp}; }
trap cleanup_delete_tmp EXIT
trap cleanup_delete_tmp SIGINT

## get query protein sequences
if [ -z ${PEP_QUERY} ]; then
    ## create a copy of F_GID in our working directory
    mkdir -p ${DIR}/id
    if [ ! -z ${F_GID} ]; then
        cp ${F_GID} ${DIR}/id/query.id.txt
    fi
    if [ ! -z ${GID} ]; then
        if [ ! -z ${F_GID} ]; then
            echo "Both --id-file and --id were provided. Combined IDs will be used."
        else
            printf '' > ${DIR}/id/query.id.txt
        fi
        echo "${GID}" | tr ',' '\n' >> ${DIR}/id/query.id.txt
        F_GID=${DIR}/id/query.id.txt
    fi
    ## extract query sequences
    echo "Extracting query sequences"
    mkdir -p ${DIR}/seq
    ${get_seq} --assembly ${FASTA} --gff ${GFF} --feature CDS \
               --gene "$(cat "${F_GID}" | tr '\n' ',' | sed 's/,\+$//')" \
               --adjust-dir --translate --out ${DIR}/seq/query.pep.fasta
else
    mkdir -p ${DIR}/seq
    cp ${PEP_QUERY} ${DIR}/seq/query.pep.fasta
fi
PEP_QUERY=${DIR}/seq/query.pep.fasta

## download Phytozome data
lookup_files=( ${PHY_LOOKUP} )
mkdir -p ${DIR}/id
f_proteome_id=${DIR}/id/query.proteome.txt
if [ "${PROTEOME_ID}" == "all" ]; then
    awk -v FS='\t' 'NR>1 {print $2}' ${GENOME_LOOKUP} > ${f_proteome_id}
else
    echo "${PROTEOME_ID}" | tr ',' '\n' > ${f_proteome_id}
fi
proteome_ids=( $(cat ${f_proteome_id} | sort | uniq | tr '\n' ' ') )

download_jgi_files () {
    local proteome_id=${1}
    local fout=${2}
    local lookup_files=${@:3}
    ## print some stuff for logging
    echo "function: download_jgi_files"
    echo "---Downloading JGI files into '${fout}'---"
    ## temporary files
    local f_tmp1=$(mktemp_f)
    local json_tmp1=$(mktemp_f)
    ## get metadata
    ## filter for proteome_id,
    ## then extract id field for organism (colname "id"; e.g. value "Phytozome-472") and file (colname "_id")
    for lookup_file in ${lookup_files[@]}; do
        python3 -c "import sys; sys.path.append('/mnt/chaelab/rachelle/src'); import data_manip as dm; get,data = dm.parse_get_data('${lookup_file}'); entry = [x for x in data if str(get(x, 'proteome_id')) == '${proteome_id}'][0]; org_id = get(entry, 'id'); file_id = get(entry, '_id'); f = open('${f_tmp1}', 'a'); _ = f.write(str(org_id) + '\t' + str(file_id) + '\n'); f.close()"
    done
    ## combine metadata together into json file
    python3 -c "import json; import sys; sys.path.append('/mnt/chaelab/rachelle/src'); import basics; import data_manip as dm; data = [x.split('\t') for x in dm.splitlines('${f_tmp1}')]; d_data = basics.split_iter_by_key(data, lambda x:x[0]); f = open('${json_tmp1}', 'w+'); d_data = {k: [x[1] for x in v] for k, v in d_data.items()}; output = {'ids': d_data, 'api_version': '2'}; _ = f.write(json.dumps(output)); f.close()"
    ## download
    curl -X POST "https://files.jgi.doe.gov/download_files/" -H "accept: application/json" -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "Content-Type: application/json" -d "@${json_tmp1}" --output ${fout}
    # curl -X POST "https://files-download.jgi.doe.gov/" -H "accept: application/json" -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "Content-Type: application/json" -d "@${json_tmp1}" --output ${fout}
    rm ${f_tmp1}
    rm ${json_tmp1}
}

## unzip
unzip_jgi_to_directory () {
    echo "function: unzip_jgi_to_directory"
    ## inputs
    local f_zip=${1}
    local dir_out=${2}
    ## create empty temporary directory
    local dir_tmp_zip=$(mktemp -p ${dir_tmp} -d )
    echo "---Temporary download directory: '${dir_tmp_zip}'---"
    echo "------- f_zip: ${f_zip} -------"
    echo "------- dir_out: ${dir_out} -------"
    mkdir -p ${dir_tmp_zip}
    ## unzip
    unzip ${f_zip} -d ${dir_tmp_zip}
    ## unzip all gz files into output directory dir_out
    ## note that files for some organisms are crazy nested and some aren't
    ## so we use find to search recursively instead of hardcoding the number of directory levels to descend
    mkdir -p ${dir_out}
    for gz in $(find ${dir_tmp_zip} -name '*.gz'); do
        local gz_basename=$(basename ${gz%*.gz})
        gunzip -c ${gz} > ${dir_out}/${gz_basename}
    done
    ## move any files that didn't require unzipping
    for f in $(find ${dir_tmp_zip} -regextype posix-egrep -regex '.+\.(fa|fasta|gff|gff3)$'); do
        mv ${f} ${dir_out}/$(basename ${f})
    done
    ## remove temporary directory
    rm -r ${dir_tmp_zip}
    ## remove zip file
    rm ${f_zip}
}

## find potential homologues
find_phytozome_homologues_v1 () {
    echo "function: find_phytozome_homologues_v1"
    local proteome_id=${1}
    local dir_inpt=${2}
    local dir_out=${3}
    local fa_pep_query=${4}
    local fa_pep_bg=${5}
    echo "---Analysis directory (dir_out): ${dir_out}---"
    echo "------- proteome_id: ${proteome_id} -------"
    echo "------- dir_inpt: ${dir_inpt} -------"
    echo "------- flank: ${FLANK_BP} -------"
    echo "------- query: ${fa_pep_query} -------"
    mkdir -p ${dir_out} ${dir_out}/id ${dir_out}/fasta ${dir_out}/bed ${dir_out}/gff
    # ## some data files
    # local fa_pep_query=${dir_proj}/data/fasta/pin-family.TAIR10.pep.fasta
    # local fa_intron3=${dir_proj}/data/fasta/pin3.TAIR10.intron3.fasta
    ## infer full name and path of each downloaded file type
    local fa_pep=${dir_inpt}/$(python3 -c "import os; fname = [f for f in os.listdir('${dir_inpt}') if 'protein.fa' in f]; print(fname[0])")
    local fa_assembly=${dir_inpt}/$(python3 -c "import os; import re; fname = [f for f in os.listdir('${dir_inpt}') if re.search('\.(fa|fasta)$', f) and 'protein.fa' not in f]; print(fname[0])")
    local gff=${dir_inpt}/$(python3 -c "import os; import re; fname = [f for f in os.listdir('${dir_inpt}') if re.search('\.(gff|gff3)$', f)]; print(fname[0])")
    echo "------- fa_pep: ${fa_pep} -------"
    echo "------- fa_assembly: ${fa_assembly} -------"
    echo "------- gff: ${gff} -------"
    ## reciprocal BLASTP
    echo "---Executing reciprocal BLASTP of query genes against proteins---"
    ${rblastgen} --dir ${dir_out}/rblastgen --seq-type p \
                 --fasta ${fa_pep_query} --bg-fasta ${fa_pep_bg} \
                 --query-fasta ${fa_pep} --relax
    ## remove blast folders because they might be massive depending on the queries
    rm -r ${dir_out}/rblastgen/blast1 ${dir_out}/rblastgen/blast2
    ## if no potential homologues, exit
    if [ ! -f ${dir_out}/rblastgen/final/recipblast.final.fasta ]; then
        return
    fi
    ## get subject ids
    echo "---Retrieving potential homologous proteins---"
    local pid_rblast=${dir_out}/rblastgen/final/recipblast.final.gid
    local fa_pep_rblast=${dir_out}/rblastgen/final/recipblast.final.fasta
    ## extract map of seqid in fasta file to pacid, transcript id, etc.
    local id_map=${dir_out}/id/${proteome_id}.recipblast.map.txt
    local tmp=$(mktemp -p ${dir_out} tmp.XXX)
    grep '>' ${fa_pep_rblast} | sed 's/^>//' > ${tmp}
    python3 -c "import sys; import itertools; sys.path.append('/mnt/chaelab/rachelle/src'); import data_manip as dm; data = [x.split(' ') for x in dm.splitlines('${tmp}')]; data = [{**{'seqid': x[0]}, **{y.split('=')[0]: y.split('=')[1] for y in x[1:]}} for x in data]; colnames = sorted(set(itertools.chain(*[x.keys() for x in data]))); colnames = ['seqid'] + [x for x in colnames if x != 'seqid']; data = [{**x, **({} if 'ID' in colnames else {'ID': ('PAC:' + x['pacid'])})} for x in data]; colnames = colnames + ([] if 'ID' in colnames else ['ID']); data = [{**{k:v for k,v in x.items() if k != 'ID'}, **{'ID': x['ID'] if '.p.v' not in x['ID'] else x['ID'].replace('.p.v', '.v')}} for x in data]; ordered_data = [[x[colname] for colname in colnames] for x in data]; dm.write_delim('${id_map}', [colnames] + ordered_data)"
    rm ${tmp}
    ## get IDs of all relevant genes
    local txt_fid=${dir_out}/id/${proteome_id}.subset-seed.fid.txt
    if [ $(head -1 ${id_map} | grep -oP '(^|\t)ID(\t|$)' | grep 'ID') ]; then
        awk -F'\t' -v col="ID" 'FNR==1 {for (c=1;$c!=col;c++);next} {print $c}' ${id_map} > ${txt_fid}
        if grep -q '\.p\.v' ${txt_fid}; then
            sed -i 's/\.p\.v/.v/' ${txt_fid}
        fi
    else
        awk -F'\t' -v col="pacid" 'FNR==1 {for (c=1;$c!=col;c++);next} {print "PAC:"$c}' ${id_map} > ${txt_fid}
    fi
    ## subset GFF for all entries related to transcripts
    local gff_rblast=${dir_out}/gff/recipblast.gff
    ${subset_gff} -f ${txt_fid} -i ${gff} -o ${gff_rblast} --family
    ## subset genome and annotations to include some flank
    echo "---Subsetting genome and annotation around potential homologues---"
    ## get IDs of all relevant genes
    local txt_gid=${dir_out}/id/${proteome_id}.subset-seed.gid.txt
    awk '$3=="gene"' ${gff_rblast} | cut -f9 | grep -oP '^ID=[^;]+|;ID=[^;]+' | sed 's/^ID=//' > ${txt_gid}
    ## subset genome and annotations to include
    local gff_subset=${dir_out}/gff/${proteome_id}.subset.gff
    local gff_subset_og=${dir_out}/gff/${proteome_id}.subset-OGcoords.gff
    local fa_subset=${dir_out}/fasta/${proteome_id}.subset.fasta
    local bed_subset=${dir_out}/bed/${proteome_id}.subset.bed
    /mnt/chaelab/rachelle/src/extract_seq_and_annotate_merge.sh --gff ${gff} --fasta ${fa_assembly} --id ${txt_gid} \
                                                                --gff-out ${gff_subset} --fasta-out ${fa_subset} \
                                                                --bed-out ${bed_subset} \
                                                                --extend ${EXTEND_BP} --flank ${FLANK_BP} \
                                                                --gff-original ${gff_subset_og} \
                                                                --parent --memsave
    ## get genbank sequence
    if [ ${GENBANK_OUT} -eq 1 ]; then
        python3 -c "import sys; sys.path.append('/mnt/chaelab/rachelle/src/'); import data_manip as dm; import extract_seq_and_annotate as esa; afasta = esa.AnnotatedFasta('${fa_assembly}', '${gff_subset_og}', name = '${proteome_id}'); fids = dm.splitlines('${txt_gid}'); esa.get_flanked_seq(afasta, fids = fids, flank = ${FLANK_BP}, gb_dir = '${dir_out}/genbank', id_as_label = True)"
    fi
}

process_proteome_v1() {
    echo "function: process_proteome_v1"
    local proteome_id="${1}"
    local dir_out=${DIR}/phytozome/${proteome_id}
    mkdir -p ${dir_out}
    ## download data files
    download_jgi_files ${proteome_id} ${dir_out}/data.zip ${PHY_LOOKUP}
    ## unzip data files
    unzip_jgi_to_directory ${dir_out}/data.zip ${dir_out}/data
    ## find homologues
    find_phytozome_homologues_v1 ${proteome_id} ${dir_out}/data ${dir_out} ${PEP_QUERY} ${PEP}
    ## delete downloaded data
    rm -r ${dir_out}/data
}

## start processing
mkdir -p ${DIR}/phytozome
mkdir -p ${DIR}/log
for proteome_id in ${proteome_ids[@]}; do
    (
        echo "============::=== Processing proteome '${proteome_id}' ==::============"
        logfile=${DIR}/log/${proteome_id}.log
        process_proteome_v1 ${proteome_id} > ${logfile} 2>&1
    ) &
    ## allow to execute up to $N jobs in parallel
    if [[ $(jobs -r -p | wc -l) -ge $PROCESSES ]]; then
        ## now there are $N jobs already running, so wait here for any job
        ## to be finished so there is a place to start the next one
        wait -n
    fi
done
wait
echo "===::== completed ==::==="
