#!/usr/bin/env Rscript

## args:
## input biosample metadata file (generated by bp_genbank2gff3)
## output file name
## optional arguments (supplied columns will be used as joining keys):
## --cs: column name of cs numbers
## --name: column name of accession names
## --id: column name of accession ids

library("argparse")
parser <- ArgumentParser(description = "extract Biosample and accession name, ID, and/or CS number from metadata, and left join with 1135, 80 MPMI, and Afican accessions metadata to make file with BioSample, ID, name, CS as column names.")
parser$add_argument("inpt", metavar="FILE", type="character", nargs=1, help="input biosample metadata file (tsv)")
parser$add_argument("outpt", metavar="FILE", type="character", nargs=1, help="output file")
## parser$add_argument("metainpt", metavar="FILE", type="character", nargs='*', help="files for joining")
parser$add_argument("--id", metavar="character", default=NULL, type="character", help="column name of accession IDs")
parser$add_argument("--cs", metavar="character", default=NULL, type="character", help="column name of CS numbers")
parser$add_argument("--name", metavar="character", default=NULL, type="character", help="column name of accession names")

args <- parser$parse_args()

## ## for debugging
## ## note that all positional arguments must be provided together
## ## i.e. './map_biosample_arath.R --cs hey booya.txt ohno.bruh baba.best ohdear.hey --id oops ' OK
## ## but './map_biosample_arath.R --cs hey booya.txt ohno.bruh --id oops baba.best ohdear.hey' not OK
## print(args$inpt)
## print(args$outpt)
## ## print(args$metainpt)
## print(args$id)
## print(args$cs)
## print(args$name)

library(tidyverse)

## parse biosample metadata
df.biosamples <- read.table(args$inpt, header = TRUE, sep = '\t')

## create left data
df.left <- data.frame(BioSample = df.biosamples$BioSample)
join_keys <- c()
if (!is.null(args$id)){
    df.left$id <- df.biosamples[,str_replace_all(args$id, ' ', '.')]
    join_keys <- c(join_keys, "id")
}
if (!is.null(args$cs)){
    df.left$CSnumber <- df.biosamples[,str_replace_all(args$cs, ' ', '.')]
    join_keys <- c(join_keys, "CSnumber")
}
if (!is.null(args$name)){
    df.left$name <- df.biosamples[,str_replace_all(args$name, ' ', '.')]
    join_keys <- c(join_keys, "name")
}

## parse right data
df.acc <- read.table("/mnt/chaelab/rachelle/data/accessions/accession_meta/athaliana_master_accessions.tsv",
                     header = TRUE, sep = '\t') %>%
    dplyr::select(id, name, CSnumber)

## merge
df.output <- left_join(df.left, df.acc, by = join_keys)
df.output <- df.output[,c("BioSample", "name", "id", "CSnumber")] %>%
    dplyr::mutate(name.in.right = name %in% df.acc$name,
                  id.in.right = id %in% df.acc$id,
                  CSnumber.in.right = CSnumber %in% df.acc$CSnumber)

## write
write.table(df.output, args$outpt, quote = FALSE, sep = '\t', row.name = FALSE)
